#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :  1098283201                          # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.aluntapps.sleepfan                                       # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : AluntApps (Contact us to aluntapps@gmail.com)
your_link                                 : 
your_city                                 : 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  
                                             

  - title                                 : About this app
    description                           : "<p>Get to sleep in 20 minutes or less with Sleep Fan. Get high quality deep sleep in no time with this APP! </p>
    <p> <br>Sleep fan helps you fall asleep faster, get high quality deep sleep, relieve stress and wake up fresh.</p> 
    <p> <br> Perfect for:
    <br> * Sleep
    <br> * Relaxing
    <br> * Noise masking
    <br> * Reduce stress
    <br> * Focusing
    <br> * Calming your mind
    <br> * Studying
    <br> * Soothing sound for baby </p>
    
    <p> <br> Features include:
      <br>  * 5 Soothing High Quality Fan Sounds / White Noise
      <br> * Fan sounds at 3 speed levels (high, medium and low)
      <br>  * Keeps running in background
      <br>  * Configurable timer to turn the fan off
      <br>  * Intuitive Spinning Fan animation </p>

<p> <br> Many people rely on the sound of their fan to help them fall asleep. But the problem is that you can't always have your fan with you!! </p>
<p> <br> But you have your iPhone or iPad with you most of the time !! So if you download this app then you have the noise of your fan with you wherever you are!</p>
<p> <br> Get a better sleep with Sleep Fan !! Download now for FREE !! </p>


    
 "
    fontawesome_icon_name                 : info-circle        


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
